### ISSUE TITLE
Add option timestep to the framework

### ISSUE THREAD

**Issue by Domsall** [stepeos/pycarmodel_calibration#3]
I am testing a new timestep-option to calibrate the models with coarse data.

Until now, the 0.04s seem to be hard-coded.

**Comment by Domsall** [comment]
@stepeos Please check modifications and merge.
The changes work on my side, although the `coveredDistance` is not fully correct anymore.

**Comment by stepeos** [comment]
I already merged but now I'm thinking it might be smarter to put it into  the data-config since it's not an 'action' but rather specific to a data set

**Comment by Domsall** [comment]
I have no preference. You can leave it as it is or change it. On my side, everything works fine, so I will close this.
